{% set name = "eo-learn-coregistration" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4743916d90daf44ccac83c30f807d965be68e1758126f8ba2047f5e8d4eac19

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7

  run:
    - eo-learn-core
    - opencv
    - python >=3.7
    - thunder-registration

test:
  imports:
    - eolearn
    - eolearn.core

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of image co-registration utilities and EOTasks
  doc_url: https://pypi.org/project/eo-learn-coregistration/
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
